# Generated by Django 2.2.7 on 2019-11-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(verbose_name='URL')),
                ('short_url', models.CharField(blank=True, max_length=30, unique=True)),
            ],
        ),
    ]
